hide:
  ansible-plan: 'Comment.Body startsWith "## Ansible Plan Results"'

post:
  ansible-plan:
    template: |
      ## Ansible Plan Results

      **Mode:** `--check --diff` (dry run)

      {{- if eq .Vars.has_changes "true" }}

      :warning: **Changes detected**
      {{- else }}

      :white_check_mark: **No changes**
      {{- end }}

      ---
      {{- range $plan := fromJson .Vars.plans_json }}

      ### {{ $plan.node }} / {{ $plan.playbook }}

      **Stats:**
      {{- range $host, $stat := $plan.stats }}
      - **{{ $host }}**: ok={{ $stat.ok }} changed={{ $stat.changed }} failures={{ $stat.failures }} skipped={{ $stat.skipped }} unreachable={{ $stat.unreachable }}
      {{- end }}
      {{- if $plan.changed_tasks }}

      **Changed Tasks ({{ len $plan.changed_tasks }}):**
      {{- range $plan.changed_tasks }}
      - {{ .name | AvoidHTMLEscape }}
      {{- end }}
      {{- end }}
      {{- if $plan.failed_tasks }}

      **Failed Tasks ({{ len $plan.failed_tasks }}):**
      {{- range $plan.failed_tasks }}
      - {{ .name | AvoidHTMLEscape }}: {{ .msg | AvoidHTMLEscape }}
      {{- end }}
      {{- end }}
      {{- if and (not $plan.changed_tasks) (not $plan.failed_tasks) }}

      No changes detected.
      {{- end }}

      ---
      {{- end }}

      *Plan executed on all nodes in parallel.*
