---
- name: Converge
  hosts: all
  tasks:
    - name: "Include user_management"
      ansible.builtin.include_role:
        name: "arch.user_management"
      vars:
        user_management_use_github_keys: true
        user_management_github_username: "boxp"