---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # Use systemd-enabled Ubuntu Noble image that matches Armbian build
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
    env:
      DEBIAN_FRONTEND: noninteractive
    # Support ARM64 platform for Orange Pi Zero 3
    platform: "${MOLECULE_DOCKER_PLATFORM:-linux/amd64}"
    # Simulate Orange Pi Zero 3 environment
    groups:
      - orange_pi_zero3
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: prepare.yml
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: /usr/bin/python3
        # Orange Pi Zero 3 specific variables
        hardware_type: orange_pi_zero3
        architecture: arm64
verifier:
  name: ansible