---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: "../../../user_management"
      vars:
        user_management_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC... test@molecule"