---
- name: Prepare Orange Pi Zero 3 simulation environment
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages for Orange Pi Zero 3 simulation
      ansible.builtin.package:
        name:
          - sudo
          - openssh-server
          - python3
          - python3-pip
          - systemd
          - rfkill
          - iproute2
          - net-tools
        state: present

    - name: Ensure systemd is running
      ansible.builtin.service:
        name: systemd-resolved
        state: started
        enabled: true
      failed_when: false

    - name: Create SSH host keys
      ansible.builtin.command:
        cmd: ssh-keygen -A
        creates: /etc/ssh/ssh_host_rsa_key