---
all:
  children:
    control_plane:
      hosts:
        shanghai-1:
          ansible_host: 192.168.10.102
          node_ip: 192.168.10.102
        shanghai-2:
          ansible_host: 192.168.10.103
          node_ip: 192.168.10.103
        shanghai-3:
          ansible_host: 192.168.10.104
          node_ip: 192.168.10.104
      vars:
        ansible_user: boxp
        ansible_ssh_common_args: '-o ProxyCommand="cloudflared access ssh --hostname %h"'
        ansible_python_interpreter: /usr/bin/python3

        # Kubernetes configuration
        kubernetes_version: "1.32"
        kubernetes_package_version: "1.32.0-1.1"
        crio_version: "1.32"

        # Cluster configuration
        cluster_vip: "192.168.10.99"
        cluster_domain: "cluster.local"
        cluster_dns: "10.96.0.10"

        # Hardware configuration
        hardware_type: "orange_pi_zero3"
        architecture: "arm64"

        # Network configuration
        network_gateway: "192.168.10.1"
        network_dns_servers:
          - "8.8.8.8"
          - "8.8.4.4"
