---
# handlers file for kube_vip

- name: Wait for kube-vip pod
  ansible.builtin.wait_for:
    path: "{{ kube_vip_manifest_dir }}/kube-vip.yaml"
    state: present
  become: true

- name: Check kube-vip pod status
  ansible.builtin.shell: |
    if [ -f /etc/kubernetes/admin.conf ]; then
      kubectl --kubeconfig=/etc/kubernetes/admin.conf get pod -n kube-system -l component=kube-vip --no-headers
    else
      echo "Kubeconfig not found, skipping pod status check"
    fi
  register: kube_vip_pod_status
  become: true
  when: ansible_virtualization_type != "docker"
  changed_when: false
  failed_when: false
