---
# Updated handlers file for network_configuration using Netplan

- name: Apply netplan configuration
  ansible.builtin.command: netplan apply
  become: true
  changed_when: true
  failed_when: false  # Allow failure in container environments without udev
  when: chroot_build is not defined or not chroot_build
