---
# Detect network interface for kube-vip

- name: Get default network interface
  ansible.builtin.shell: |
    set -o pipefail
    ip route show default | awk '/default/ {print $5}' | head -n1
  args:
    executable: /bin/bash
  register: default_interface
  changed_when: false
  check_mode: false

- name: Set detected interface
  ansible.builtin.set_fact:
    kube_vip_interface: "{{ default_interface.stdout }}"
  when: default_interface.stdout != ""

- name: Fallback to eth0 if no default route found
  ansible.builtin.set_fact:
    kube_vip_interface: "end0"
  when: default_interface.stdout == ""

- name: Display detected interface
  ansible.builtin.debug:
    msg: "Detected network interface: {{ kube_vip_interface }}"
