---
# Main tasks file for kube_vip

- name: Detect chroot build environment
  ansible.builtin.set_fact:
    is_chroot_build: "{{ chroot_build | default(false) | bool or (ansible_env.PWD | default('') | regex_search('/tmp/.*rootfs')) is not none }}"

- name: Debug chroot detection
  ansible.builtin.debug:
    msg: "Chroot build detected: {{ is_chroot_build }}"
  when: is_chroot_build

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - kube_vip_vip is defined
      - kube_vip_vip != ""
    fail_msg: "kube_vip_vip must be set to a valid IP address"

- name: Include network interface detection
  ansible.builtin.include_tasks: detect_interface.yml
  when:
    - kube_vip_auto_detect_interface
    - kube_vip_interface == ""

- name: Validate network interface
  ansible.builtin.assert:
    that:
      - kube_vip_interface is defined
      - kube_vip_interface != ""
    fail_msg: "kube_vip_interface must be set or auto-detected"

- name: Create kube-vip configuration directory
  ansible.builtin.file:
    path: "{{ kube_vip_config_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Deploy kube-vip static pod manifest
  ansible.builtin.template:
    src: kube-vip.yaml.j2
    dest: "{{ kube_vip_manifest_dir }}/kube-vip.yaml"
    mode: '0644'
  become: true
  notify: Wait for kube-vip pod
