---
# Create RBAC resources for kube-vip

- name: Create kube-vip ServiceAccount
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kube-vip
        namespace: kube-system
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Create kube-vip ClusterRole
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: kube-vip
      rules:
        - apiGroups: [""]
          resources: ["services", "endpoints"]
          verbs: ["list", "get", "watch", "update"]
        - apiGroups: [""]
          resources: ["nodes"]
          verbs: ["list", "get", "watch", "update", "patch"]
        - apiGroups: ["coordination.k8s.io"]
          resources: ["leases"]
          verbs: ["list", "get", "watch", "create", "update", "delete"]
        - apiGroups: ["discovery.k8s.io"]
          resources: ["endpointslices"]
          verbs: ["list", "get", "watch", "update"]
    kubeconfig: /etc/kubernetes/admin.conf
  become: true

- name: Create kube-vip ClusterRoleBinding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: kube-vip
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: kube-vip
      subjects:
        - kind: ServiceAccount
          name: kube-vip
          namespace: kube-system
    kubeconfig: /etc/kubernetes/admin.conf
  become: true
