---
- name: Configure Shanghai-2 control plane node
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    # Node-specific configuration
    node_hostname: "shanghai-2"
    node_ip: "192.168.10.103"
    cluster_vip: "192.168.10.99"
    cluster_domain: "cluster.local"
    cluster_dns: "10.96.0.10"

    # Kubernetes configuration
    kubernetes_version: "1.32"
    kubernetes_package_version: "1.32.0-1.1"
    crio_version: "1.32"

    # Hardware configuration
    hardware_type: "orange_pi_zero3"
    architecture: "arm64"

    # Network configuration
    network_gateway: "192.168.10.1"
    network_dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ node_hostname }}"

    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ node_hostname }}"

    - name: Configure static IP with netplan
      ansible.builtin.copy:
        content: |
          network:
            version: 2
            renderer: systemd
            ethernets:
              eth0:
                dhcp4: false
                addresses:
                  - {{ node_ip }}/24
                gateway4: {{ network_gateway }}
                nameservers:
                  addresses: {{ network_dns_servers }}
        dest: /etc/netplan/01-armbian-static.yaml
        mode: '0644'

    - name: Remove dhcp configuration
      ansible.builtin.file:
        path: /etc/netplan/10-dhcp-all-interfaces.yaml
        state: absent

    - name: Deploy kube-vip for cluster VIP
      include_role:
        name: kube_vip
      vars:
        kube_vip_vip: "{{ cluster_vip }}"
        kube_vip_interface: "eth0"


    - name: Create directories for kubeadm
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/kubeadm
        - /etc/kubernetes/pki

    - name: Create first-boot initialization script
      ansible.builtin.copy:
        content: |
          #!/bin/bash

          # Wait for network to be ready
          sleep 30

          # Apply network configuration
          netplan apply

          # Start and enable services
          systemctl enable --now crio
          systemctl enable --now kubelet

          echo "Shanghai-2 node ready for manual cluster join"
          echo "Use: kubeadm join <cluster-endpoint> --token <token> --discovery-token-ca-cert-hash <hash> --control-plane"
        dest: /usr/local/bin/init-shanghai-2.sh
        mode: '0755'

    - name: Create systemd service for first-boot initialization
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Shanghai-2 node initialization
          After=network-online.target
          Wants=network-online.target
          ConditionPathExists=!/var/lib/shanghai-2-initialized

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/init-shanghai-2.sh
          ExecStartPost=/bin/touch /var/lib/shanghai-2-initialized
          RemainAfterExit=true

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/init-shanghai-2.service
        mode: '0644'

    - name: Enable shanghai-2 initialization service
      ansible.builtin.systemd:
        name: init-shanghai-2.service
        enabled: true
        daemon_reload: true
