---
# handlers file for cloudflare_cli

- name: restart cloudflared
  ansible.builtin.systemd:
    name: "{{ cloudflare_cli_service_name }}"
    state: restarted
    daemon_reload: true
  become: true
  when: cloudflare_cli_enable_service