# Fetch the Tailscale auth key from AWS SSM (generated by terraform/tailscale/lolice).
data "aws_ssm_parameter" "tailscale_auth_key" {
  name            = var.tailscale_auth_key_ssm_path
  with_decryption = true
}

locals {
  cloud_init_template = <<-CLOUDINIT
    #cloud-config
    package_update: true
    package_upgrade: false

    packages:
      - curl
      - jq

    runcmd:
      - |
        set -e
        # Install Tailscale
        curl -fsSL https://tailscale.com/install.sh | sh
        # Bring Tailscale up with the pre-authorized key
        tailscale up \
          --authkey="${data.aws_ssm_parameter.tailscale_auth_key.value}" \
          --hostname="HOSTNAME_PLACEHOLDER" \
          --advertise-tags="tag:cloud-control-plane" \
          --accept-routes
        # Enable IP forwarding for Kubernetes
        echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/99-k8s.conf
        echo 'net.ipv6.conf.all.forwarding = 1' >> /etc/sysctl.d/99-k8s.conf
        sysctl --system
    CLOUDINIT
}

locals {
  cloud_init_cp1 = replace(local.cloud_init_template, "HOSTNAME_PLACEHOLDER", "oracle-cp-1")
  cloud_init_cp2 = replace(local.cloud_init_template, "HOSTNAME_PLACEHOLDER", "oracle-cp-2")
}
