---
# System preparation tasks for Kubernetes

- name: Disable swap
  ansible.builtin.command: swapoff -a
  become: true
  when: kubernetes_disable_swap
  changed_when: false

- name: Remove swap from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent
  become: true
  when: kubernetes_disable_swap

- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ kernel_modules }}"
  when: kubernetes_enable_modules and not (ansible_virtualization_type | default('') == 'docker' and item == 'br_netfilter')

- name: Ensure kernel modules are loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
    mode: '0644'
  become: true
  loop: "{{ kernel_modules }}"
  when: kubernetes_enable_modules and not (ansible_virtualization_type | default('') == 'docker' and item == 'br_netfilter')

- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  become: true
  loop: "{{ sysctl_config | dict2items }}"
  when: not (ansible_virtualization_type | default('') == 'docker' and item.key is match('net\.bridge\..*'))

- name: Create sysctl configuration file
  ansible.builtin.template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
  become: true
  notify: Reload sysctl

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  become: true
