---
# System preparation tasks for Kubernetes

- name: Check if running in chroot environment
  ansible.builtin.stat:
    path: /proc/1/root/.
  register: chroot_check
  changed_when: false
  failed_when: false

- name: Set chroot fact
  ansible.builtin.set_fact:
    is_chroot: "{{ chroot_check.stat.ino is not defined or chroot_check.stat.ino != 2 }}"

- name: Disable swap
  ansible.builtin.command: swapoff -a
  become: true
  when:
    - kubernetes_disable_swap
    - not is_chroot
  changed_when: false

- name: Skip swap disable in chroot
  ansible.builtin.debug:
    msg: "Skipping swapoff in chroot environment. Swap will be disabled via fstab."
  when:
    - kubernetes_disable_swap
    - is_chroot

- name: Remove swap from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent
  become: true
  when: kubernetes_disable_swap

- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ kernel_modules }}"
  when:
    - kubernetes_enable_modules
    - not is_chroot
    - not (ansible_virtualization_type | default('') == 'docker' and item == 'br_netfilter')

- name: Skip kernel module loading in chroot
  ansible.builtin.debug:
    msg: "Skipping kernel module loading in chroot environment. Modules will be loaded on first boot."
  when:
    - kubernetes_enable_modules
    - is_chroot

- name: Ensure kernel modules are loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
    mode: '0644'
  become: true
  loop: "{{ kernel_modules }}"
  when:
    - kubernetes_enable_modules
    - not (ansible_virtualization_type | default('') == 'docker' and item == 'br_netfilter')

- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ not is_chroot }}"
    state: present
    reload: "{{ not is_chroot }}"
  become: true
  loop: "{{ sysctl_config | dict2items }}"
  when:
    - not (ansible_virtualization_type | default('') == 'docker' and item.key is match('net\.bridge\..*'))
    - not (is_chroot and item.key is match('net\.bridge\..*'))

- name: Skip sysctl runtime configuration in chroot
  ansible.builtin.debug:
    msg: "Skipping sysctl runtime configuration in chroot environment. Parameters will be applied on first boot."
  when: is_chroot

- name: Create sysctl configuration file
  ansible.builtin.template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
  become: true
  notify: Reload sysctl
