---
# System preparation tasks for Kubernetes

- name: Check if running in chroot environment
  ansible.builtin.stat:
    path: /proc/1/root/.
  register: chroot_check
  changed_when: false
  failed_when: false

- name: Set chroot fact
  ansible.builtin.set_fact:
    is_chroot: "{{ chroot_check.stat.ino is not defined or chroot_check.stat.ino != 2 }}"

- name: Disable swap
  ansible.builtin.command: swapoff -a
  become: true
  when:
    - kubernetes_disable_swap
    - not is_chroot
  changed_when: false

- name: Skip swap disable in chroot
  ansible.builtin.debug:
    msg: "Skipping swapoff in chroot environment. Swap will be disabled via fstab."
  when:
    - kubernetes_disable_swap
    - is_chroot

- name: Remove swap from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent
  become: true
  when: kubernetes_disable_swap

- name: Check if zswap is enabled
  ansible.builtin.stat:
    path: /sys/module/zswap/parameters/enabled
  register: zswap_enabled_check
  when:
    - kubernetes_disable_swap
    - not is_chroot

- name: Disable zswap at runtime
  ansible.builtin.shell: echo 0 > /sys/module/zswap/parameters/enabled
  become: true
  when:
    - kubernetes_disable_swap
    - not is_chroot
    - zswap_enabled_check.stat.exists
  changed_when: false

- name: Check if Armbian boot environment file exists
  ansible.builtin.stat:
    path: /boot/armbianEnv.txt
  register: armbian_env_check
  when: kubernetes_disable_swap

- name: Add zswap.enabled=0 to Armbian boot environment
  ansible.builtin.lineinfile:
    path: /boot/armbianEnv.txt
    regexp: '^extraargs='
    line: 'extraargs=zswap.enabled=0'
    create: false
  become: true
  when:
    - kubernetes_disable_swap
    - armbian_env_check.stat.exists
  register: armbian_zswap_disabled

- name: Append zswap.enabled=0 to existing extraargs in Armbian boot environment
  ansible.builtin.replace:
    path: /boot/armbianEnv.txt
    regexp: '^(extraargs=(?!.*zswap\.enabled=0).*)$'
    replace: '\1 zswap.enabled=0'
  become: true
  when:
    - kubernetes_disable_swap
    - armbian_env_check.stat.exists
    - armbian_zswap_disabled is not changed

- name: Check if GRUB configuration exists
  ansible.builtin.stat:
    path: /etc/default/grub
  register: grub_config_check
  when: kubernetes_disable_swap

- name: Add zswap.enabled=0 to GRUB configuration
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet zswap.enabled=0"'
    backup: true
  become: true
  when:
    - kubernetes_disable_swap
    - grub_config_check.stat.exists
    - not armbian_env_check.stat.exists
  notify: Update grub

- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ kernel_modules }}"
  when:
    - kubernetes_enable_modules
    - not is_chroot
    - not (ansible_virtualization_type | default('') == 'docker' and item == 'br_netfilter')

- name: Skip kernel module loading in chroot
  ansible.builtin.debug:
    msg: "Skipping kernel module loading in chroot environment. Modules will be loaded on first boot."
  when:
    - kubernetes_enable_modules
    - is_chroot

- name: Ensure kernel modules are loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
    mode: '0644'
  become: true
  loop: "{{ kernel_modules }}"
  when:
    - kubernetes_enable_modules
    - not (ansible_virtualization_type | default('') == 'docker' and item == 'br_netfilter')

- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ not is_chroot }}"
    state: present
    reload: "{{ not is_chroot }}"
  become: true
  loop: "{{ sysctl_config | dict2items }}"
  when:
    - not (ansible_virtualization_type | default('') == 'docker' and item.key is match('net\.bridge\..*'))
    - not (is_chroot and item.key is match('net\.bridge\..*'))

- name: Skip sysctl runtime configuration in chroot
  ansible.builtin.debug:
    msg: "Skipping sysctl runtime configuration in chroot environment. Parameters will be applied on first boot."
  when: is_chroot

- name: Create sysctl configuration file
  ansible.builtin.template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
  become: true
  notify: Reload sysctl
