---
galaxy_info:
  author: boxp
  description: Install and configure Cloudflare CLI (cloudflared) for Orange Pi Zero 3
  company: Personal Infrastructure
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - cloudflare
    - cli
    - tunnel
    - arm64
    - orangepi

dependencies: []
