---
- name: Prepare Orange Pi Zero 3 simulation environment
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages for Orange Pi Zero 3 simulation
      ansible.builtin.package:
        name:
          - sudo
          - openssh-server
          - python3
          - python3-pip
          - systemd
          - rfkill
          - iproute2
          - net-tools
          - wireless-tools
        state: present

    - name: Create network interfaces directory
      ansible.builtin.file:
        path: /etc/network/interfaces.d
        state: directory
        mode: '0755'

    - name: Ensure systemd is running
      ansible.builtin.service:
        name: systemd-resolved
        state: started
        enabled: true
      failed_when: false

    - name: Create SSH host keys
      ansible.builtin.command:
        cmd: ssh-keygen -A
        creates: /etc/ssh/ssh_host_rsa_key

    # Simulate Orange Pi Zero 3 hardware environment
    - name: Create mock rfkill devices for testing
      ansible.builtin.shell: |
        mkdir -p /sys/class/rfkill/rfkill0
        mkdir -p /sys/class/rfkill/rfkill1
        echo "wlan" > /sys/class/rfkill/rfkill0/type || true
        echo "bluetooth" > /sys/class/rfkill/rfkill1/type || true
      failed_when: false