---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if netplan configuration file exists
      ansible.builtin.stat:
        path: /etc/netplan/01-static-eth0.yaml
      register: netplan_config

    - name: Assert netplan configuration exists
      ansible.builtin.assert:
        that:
          - netplan_config.stat.exists
        fail_msg: "Netplan configuration file does not exist"

    - name: Read netplan configuration
      ansible.builtin.slurp:
        src: /etc/netplan/01-static-eth0.yaml
      register: netplan_content

    - name: Decode netplan configuration
      ansible.builtin.set_fact:
        netplan_config_content: "{{ netplan_content.content | b64decode }}"

    - name: Assert static IP configuration
      ansible.builtin.assert:
        that:
          - "'dhcp4: false' in netplan_config_content"
          - "'192.168.10.' in netplan_config_content"
          - "'renderer: networkd' in netplan_config_content"
        fail_msg: "Static IP configuration not found"

    - name: Check if WiFi is disabled
      ansible.builtin.command: rfkill list wifi
      register: wifi_status
      changed_when: false
      failed_when: false

    - name: Check if Bluetooth is disabled
      ansible.builtin.command: rfkill list bluetooth
      register: bt_status
      changed_when: false
      failed_when: false

    - name: Assert WiFi and Bluetooth are blocked
      ansible.builtin.assert:
        that:
          - wifi_status.rc != 0 or 'blocked: yes' in wifi_status.stdout
          - bt_status.rc != 0 or 'blocked: yes' in bt_status.stdout
        fail_msg: "WiFi or Bluetooth is not disabled"
      when: wifi_status.rc == 0 or bt_status.rc == 0