---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - control_plane
    env:
      DEBIAN_FRONTEND: noninteractive
    platform: ${MOLECULE_DOCKER_PLATFORM:-linux/amd64}
provisioner:
  name: ansible
  inventory:
    group_vars:
      control_plane:
        kube_vip_vip: "192.168.100.10"
        kube_vip_auto_detect_interface: true
verifier:
  name: ansible