---
- name: Prepare kube-vip test environment
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.package:
        name:
          - systemd
          - iproute2
          - iptables
          - arping
        state: present

    - name: Create Kubernetes directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/kubernetes
        - /etc/kubernetes/manifests

    - name: Create mock kubeconfig for testing
      ansible.builtin.copy:
        dest: /etc/kubernetes/admin.conf
        content: |
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: https://127.0.0.1:6443
            name: kubernetes
          contexts:
          - context:
              cluster: kubernetes
              user: kubernetes-admin
            name: kubernetes-admin@kubernetes
          current-context: kubernetes-admin@kubernetes
          users:
          - name: kubernetes-admin
        mode: '0600'

    - name: Ensure systemd is running
      ansible.builtin.systemd:
        daemon_reload: true