---
- name: Verify kube-vip installation
  hosts: all
  become: true
  tasks:
    - name: Check if kube-vip manifest exists
      ansible.builtin.stat:
        path: /etc/kubernetes/manifests/kube-vip.yaml
      register: manifest_stat

    - name: Assert manifest exists
      ansible.builtin.assert:
        that:
          - manifest_stat.stat.exists
        fail_msg: "kube-vip manifest not found"

    - name: Read kube-vip manifest
      ansible.builtin.slurp:
        src: /etc/kubernetes/manifests/kube-vip.yaml
      register: manifest_content

    - name: Parse manifest YAML
      ansible.builtin.set_fact:
        manifest_yaml: "{{ manifest_content.content | b64decode | from_yaml }}"

    - name: Verify manifest configuration
      ansible.builtin.assert:
        that:
          - manifest_yaml.metadata.name == "kube-vip"
          - manifest_yaml.metadata.namespace == "kube-system"
          - manifest_yaml.spec.hostNetwork == true
          - "'NET_ADMIN' in manifest_yaml.spec.containers[0].securityContext.capabilities.add"
          - "'NET_RAW' in manifest_yaml.spec.containers[0].securityContext.capabilities.add"
        fail_msg: "kube-vip manifest configuration incorrect"

    - name: Check VIP address is configured
      ansible.builtin.assert:
        that:
          - manifest_yaml.spec.containers[0].env | selectattr('name', 'equalto', 'address') | list | length > 0
          - manifest_yaml.spec.containers[0].env | selectattr('name', 'equalto', 'address') | map(attribute='value') | first == "192.168.10.99"
        fail_msg: "VIP address not properly configured"

    - name: Check interface is configured
      ansible.builtin.assert:
        that:
          - manifest_yaml.spec.containers[0].env | selectattr('name', 'equalto', 'vip_interface') | list | length > 0
        fail_msg: "Network interface not configured"

    - name: Verify kube-vip configuration directory
      ansible.builtin.stat:
        path: /etc/kube-vip
      register: config_dir

    - name: Assert configuration directory exists
      ansible.builtin.assert:
        that:
          - config_dir.stat.exists
          - config_dir.stat.isdir
        fail_msg: "kube-vip configuration directory not created"