name: Ansible Lint

on:
  pull_request:
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-lint.yml'
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          cd ansible
          uv sync

      - name: Run ansible-lint
        run: |
          cd ansible
          source .venv/bin/activate
          ansible-lint

      - name: Run Molecule tests
        run: |
          cd ansible
          source .venv/bin/activate
          for role in roles/*/; do
            if [ -d "$role/molecule" ]; then
              echo "Testing role: $role"
              cd "$role"
              molecule test
              cd - > /dev/null
            fi
          done