name: Create drift issues
on:
  workflow_dispatch:
    inputs: {}
  # schedule:
  #   # daily
  #   - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          # issues:write - Create issues
          permissions: >-
            {
              "issues": "write"
            }
          # repository where Drift Detection issues are hosted
          repositories: >-
            ["${{github.event.repository.name}}"]

      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.25.0
        env:
          AQUA_GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - run: tfaction create-drift-issues
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
