---
name: plan-aggregator
on:
  workflow_call:
    inputs:
      plan_result:
        description: "JSON array of plan job results"
        required: false
        type: string
        default: "[]"
      has_terraform_targets:
        description: "Whether there are any terraform targets to plan"
        required: false
        type: boolean
        default: false
    outputs:
      result:
        description: "Result of the aggregation (success or failure)"
        value: ${{ jobs.aggregate-plan-results.outputs.result }}

jobs:
  aggregate-plan-results:
    name: "Aggregate Plan Results"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # このジョブは常に実行される
    outputs:
      result: ${{ steps.check-results.outputs.result }}
    steps:
      - name: Check plan results
        id: check-results
        run: |
          echo "Checking plan results..."
          
          # 入力がない場合は空の配列をデフォルト値として使用
          PLAN_RESULTS='${{ inputs.plan_result }}'
          if [ "$PLAN_RESULTS" = "" ]; then
            PLAN_RESULTS="[]"
          fi
          
          # Terraform対象があるかどうか
          HAS_TARGETS="${{ inputs.has_terraform_targets }}"
          
          # 結果を解析
          echo "Plan results: $PLAN_RESULTS"
          echo "Has terraform targets: $HAS_TARGETS"
          
          # 成功したplanの数をカウント
          SUCCESS_COUNT=$(echo "$PLAN_RESULTS" | jq '[.[] | select(.result == "success")] | length')
          TOTAL_COUNT=$(echo "$PLAN_RESULTS" | jq 'length')
          
          echo "Total plan jobs: $TOTAL_COUNT"
          echo "Successful plan jobs: $SUCCESS_COUNT"
          
          # 判定ロジック:
          # 1. Terraform対象がない場合は成功
          # 2. 一つでも成功したplanがある場合は成功
          if [ "$HAS_TARGETS" = "false" ] || [ "$SUCCESS_COUNT" -gt 0 ]; then
            echo "✅ Plan check passed!"
            echo "result=success" >> "$GITHUB_OUTPUT"
          else
            echo "❌ All plan jobs failed!"
            echo "result=failure" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Plan Result
        run: |
          if [ "${{ steps.check-results.outputs.result }}" = "success" ]; then
            echo "✅ Plan check passed!"
            exit 0
          else
            echo "❌ Plan check failed!"
            exit 1
          fi