---
name: plan
on:
  workflow_call:
    inputs:
      targets:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
      gh_cloudflare_api_token:
        required: true
    outputs:
      result:
        description: "JSON array of plan job results"
        value: ${{ jobs.collect-results.outputs.results }}

jobs:
  plan:
    name: "plan (${{matrix.target.target}})"
    runs-on: ${{matrix.target.runs_on}}
    permissions:
      id-token: write # For OIDC
      contents: read # To checkout private repositories
    env:
      TFACTION_TARGET: ${{matrix.target.target}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
      GH_COMMENT_SHA1: ${{inputs.ref}}
      TFCMT_SHA: ${{inputs.ref}}
    strategy:
      fail-fast: true
      matrix:
        target: ${{fromJSON(inputs.targets)}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{inputs.ref}}

      - name: Generate token (aqua)
        id: aqua_installer_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          permissions: >-
            {}
          repositories: >-
            []

      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.45.0
        env:
          AQUA_GITHUB_TOKEN: ${{steps.aqua_installer_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction/export-secrets@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6 # v1.15.5
        with:
          secrets: ${{toJSON(secrets)}}

      - name: Generate token to download private Terraform Modules
        id: gh_setup_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.gh_app_id }}
          private_key: ${{ secrets.gh_app_private_key }}
          # If you use private registries, contents:read is required
          permissions: >-
            {
              "contents": "read"
            }
          # private repositories hosting private modules
          repositories: >-
            []

      # This is required to download private modules in `terraform init`
      - run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{steps.gh_setup_token.outputs.token}}

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          # issues:write - Create labels
          # pull_requests:write - Post comments and set labels
          # contents:write - Push commits
          permissions: >-
            {
              "pull_requests": "write",
              "issues": "write",
              "contents": "write"
            }
          repositories: >-
            ["${{github.event.repository.name}}"]

      - uses: suzuki-shunsuke/tfaction/setup@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6 # v1.15.5
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}} # For GitHub Provider

      - uses: suzuki-shunsuke/tfaction/get-target-config@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6 # v1.15.5
        id: target-config

      - name: Generate token (pull request write)
        id: pull_request_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          permissions: >-
            {
              "pull_requests": "write"
            }
          repositories: >-
            ["${{github.event.repository.name}}"]

      - run: |
          set -euo pipefail
          tfprovidercheck -v
          github-comment exec -- terraform version -json | github-comment exec -- tfprovidercheck
        working-directory: ${{ steps.target-config.outputs.working_directory }}
        env:
          TFPROVIDERCHECK_CONFIG_BODY: |
            providers:
              - name: registry.terraform.io/cloudflare/cloudflare
              - name: registry.terraform.io/hashicorp/aws
              - name: registry.terraform.io/hashicorp/google
              - name: registry.terraform.io/hashicorp/null
              - name: registry.terraform.io/hashicorp/tls
              - name: registry.terraform.io/hashicorp/random
              - name: registry.terraform.io/hashicorp/time
              - name: registry.terraform.io/integrations/github
          GITHUB_TOKEN: ${{steps.pull_request_token.outputs.token}} # For github-comment

      - uses: suzuki-shunsuke/tfaction/test@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6 # v1.15.5
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}} # For GitHub Provider and reviewdog and github-comment
          CLOUDFLARE_API_TOKEN: ${{secrets.gh_cloudflare_api_token}} # For cloudflare provider

      - uses: suzuki-shunsuke/tfaction/plan@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6 # v1.15.5
        id: plan
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}} # For GitHub Provider and tfcmt and github-comment
          CLOUDFLARE_API_TOKEN: ${{secrets.gh_cloudflare_api_token}} # For cloudflare provider
      
      # 各planジョブの結果を出力
      - name: Set job result
        id: set-result
        if: always()
        run: |
          echo "status=${{ job.status }}" >> "$GITHUB_OUTPUT"
          echo "target=${{ matrix.target.target }}" >> "$GITHUB_OUTPUT"

  # 全てのplanジョブの結果を収集するジョブ
  collect-results:
    name: "Collect Plan Results"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: plan
    if: always()
    outputs:
      results: ${{ steps.collect.outputs.results }}
    steps:
      - name: Collect results
        id: collect
        run: |
          # 全てのplanジョブの結果を収集
          RESULTS='['
          
          # needs.plan.result が成功/失敗/スキップのいずれかを示す
          # needs.plan.outputs は各ジョブの出力を含む
          
          # マトリックスジョブの結果を処理
          MATRIX_CONTEXT='${{ toJSON(needs.plan) }}'
          echo "Matrix context: $MATRIX_CONTEXT"
          
          # jqを使って直接結果を生成
          TARGETS_JSON='${{ toJSON(fromJSON(inputs.targets)) }}'
          JOB_RESULT=$(echo "$MATRIX_CONTEXT" | jq -r '.result')
          
          # jqを使って配列を構築
          RESULTS=$(echo "$TARGETS_JSON" | jq --arg result "$JOB_RESULT" '[.[] | {target: .target, result: $result}]')
          echo "results=$RESULTS" >> "$GITHUB_OUTPUT"
          echo "Collected results: $RESULTS"
