---
name: test
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
    secrets:
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false
      gh_cloudflare_api_token:
        required: false
      terraform_private_module_ssh_key: # This isn't needed if you don't use SSH key to checkout private Terraform Modules
        required: false
      secrets:
        required: false
    outputs:
      plan_aggregator_result:
        description: "Result of the plan-aggregator job"
        value: ${{ jobs.plan-aggregator.outputs.result }}

env:
  TFACTION_IS_APPLY: 'false'
  GH_COMMENT_SHA1: ${{inputs.ref}}
  TFCMT_SHA: ${{inputs.ref}}

permissions: {}

jobs:
  setup:
    uses: ./.github/workflows/wc-setup.yaml
    with:
      ref: ${{inputs.ref}}
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
    permissions:
      contents: read

  test-module:
    uses: ./.github/workflows/wc-test-module.yaml
    needs: setup
    # if services is empty, the build job is skipped
    if: "join(fromJSON(needs.setup.outputs.modules), '') != ''"
    with:
      modules: ${{needs.setup.outputs.modules}}
      ref: ${{inputs.ref}}
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
    permissions:
      contents: read

  plan:
    uses: ./.github/workflows/wc-plan.yaml
    needs: setup
    # if services is empty, the build job is skipped
    if: "join(fromJSON(needs.setup.outputs.targets), '') != ''"
    with:
      targets: ${{needs.setup.outputs.targets}}
      ref: ${{inputs.ref}}
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
      gh_cloudflare_api_token: ${{secrets.gh_cloudflare_api_token}}
    permissions:
      id-token: write
      contents: read
  
  # 新しいアグリゲータージョブを追加
  plan-aggregator:
    uses: ./.github/workflows/wc-plan-aggregator.yaml
    needs: [setup, plan]
    if: always() # 常に実行する
    with:
      # planジョブが実行された場合のみ結果を渡す
      plan_result: ${{ needs.plan.result != '' && needs.plan.outputs.result || '[]' }}
      has_terraform_targets: ${{ join(fromJSON(needs.setup.outputs.targets), '') != '' }}
